import { NextRequest, NextResponse } from 'next/server'
import JSZip from 'jszip'
import { Capsule } from '@/types/capsule'
import { withCsrfProtection } from '@/lib/csrf'

interface CanvasItem {
  id: string
  capsule: Capsule
  props?: Record<string, any>
}

/**
 * POST /api/canvas/export
 * Export canvas items as a Next.js project
 * SECURITY: Protected with CSRF
 */
export const POST = withCsrfProtection(async (req: NextRequest) => {
  try {
    const { canvasItems } = await req.json() as { canvasItems: CanvasItem[] }

    if (!canvasItems || canvasItems.length === 0) {
      return NextResponse.json(
        { error: 'No canvas items provided' },
        { status: 400 }
      )
    }

    const zip = new JSZip()

    // 1. package.json
    const packageJson = {
      name: 'hublab-exported-app',
      version: '1.0.0',
      private: true,
      scripts: {
        dev: 'next dev',
        build: 'next build',
        start: 'next start',
        lint: 'next lint'
      },
      dependencies: {
        react: '^18.2.0',
        'react-dom': '^18.2.0',
        next: '^14.0.0',
        'lucide-react': '^0.263.1'
      },
      devDependencies: {
        '@types/node': '^20.0.0',
        '@types/react': '^18.2.0',
        '@types/react-dom': '^18.2.0',
        autoprefixer: '^10.4.16',
        postcss: '^8.4.31',
        tailwindcss: '^3.3.5',
        typescript: '^5.2.2'
      }
    }
    zip.file('package.json', JSON.stringify(packageJson, null, 2))

    // 2. next.config.js
    const nextConfig = `/** @type {import('next').NextConfig} */
const nextConfig = {}

module.exports = nextConfig
`
    zip.file('next.config.js', nextConfig)

    // 3. tsconfig.json
    const tsConfig = {
      compilerOptions: {
        target: 'ES2017',
        lib: ['dom', 'dom.iterable', 'esnext'],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: 'esnext',
        moduleResolution: 'bundler',
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: 'preserve',
        incremental: true,
        plugins: [{ name: 'next' }],
        paths: {
          '@/*': ['./*']
        }
      },
      include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
      exclude: ['node_modules']
    }
    zip.file('tsconfig.json', JSON.stringify(tsConfig, null, 2))

    // 4. tailwind.config.ts
    const tailwindConfig = `import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
export default config
`
    zip.file('tailwind.config.ts', tailwindConfig)

    // 5. postcss.config.js
    const postcssConfig = `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`
    zip.file('postcss.config.js', postcssConfig)

    // 6. app/globals.css
    const globalsCss = `@tailwind base;
@tailwind components;
@tailwind utilities;
`
    zip.file('app/globals.css', globalsCss)

    // 7. app/layout.tsx
    const layoutTsx = `import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'HubLab Exported App',
  description: 'Generated by HubLab Visual Canvas',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body>{children}</body>
    </html>
  )
}
`
    zip.file('app/layout.tsx', layoutTsx)

    // 8. Generar componentes individuales
    const componentImports: string[] = []
    const componentUsage: string[] = []

    canvasItems.forEach((item, index) => {
      const componentName = `Component${index + 1}`
      const fileName = `${componentName}.tsx`

      // Limpiar código de la cápsula
      let componentCode = item.capsule.code

      // Reemplazar export default con nombre específico
      componentCode = componentCode.replace(
        /export default function \w+/g,
        `export default function ${componentName}`
      )

      // Guardar componente
      zip.file(`components/${fileName}`, componentCode)

      // Registrar import y uso
      componentImports.push(`import ${componentName} from '@/components/${componentName}'`)

      const propsStr = item.props && Object.keys(item.props).length > 0
        ? ` {...${JSON.stringify(item.props)}}`
        : ''
      componentUsage.push(`      <${componentName}${propsStr} />`)
    })

    // 9. app/page.tsx (página principal)
    const pageTsx = `'use client'

${componentImports.join('\n')}

export default function Home() {
  return (
    <main className="min-h-screen p-8">
      <div className="max-w-7xl mx-auto space-y-6">
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-gray-900 mb-2">
            Mi App de HubLab
          </h1>
          <p className="text-gray-600">
            Generada con HubLab Visual Canvas
          </p>
        </div>

        <div className="space-y-6">
${componentUsage.join('\n')}
        </div>
      </div>
    </main>
  )
}
`
    zip.file('app/page.tsx', pageTsx)

    // 10. README.md
    const readme = `# HubLab Exported App

Esta aplicación fue generada automáticamente usando **HubLab Visual Canvas**.

## Componentes incluidos

${canvasItems.map((item, i) => `${i + 1}. **${item.capsule.name}** - ${item.capsule.description}`).join('\n')}

## Comenzar

1. Instala las dependencias:

\`\`\`bash
npm install
\`\`\`

2. Ejecuta el servidor de desarrollo:

\`\`\`bash
npm run dev
\`\`\`

3. Abre [http://localhost:3000](http://localhost:3000) en tu navegador.

## Tecnologías

- Next.js 14
- React 18
- TypeScript
- Tailwind CSS
- Lucide React (iconos)

## Personalización

Puedes editar los componentes en la carpeta \`components/\` y la página principal en \`app/page.tsx\`.

---

Generado por [HubLab](https://hublab.dev) - ${new Date().toLocaleDateString()}
`
    zip.file('README.md', readme)

    // 11. .gitignore
    const gitignore = `# dependencies
/node_modules
/.pnp
.pnp.js

# testing
/coverage

# next.js
/.next/
/out/

# production
/build

# misc
.DS_Store
*.pem

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# local env files
.env*.local

# vercel
.vercel

# typescript
*.tsbuildinfo
next-env.d.ts
`
    zip.file('.gitignore', gitignore)

    // 12. Generar ZIP
    const zipBlob = await zip.generateAsync({ type: 'blob' })

    return new NextResponse(zipBlob, {
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="hublab-app-${Date.now()}.zip"`
      }
    })
  } catch (error) {
    console.error('Export error:', error)
    return NextResponse.json(
      { error: 'Failed to export project' },
      { status: 500 }
    )
  }
})
