/**
 * Landing Page Component
 * Generated by HubLab Studio V2
 * https://hublab.dev/studio-v2
 *
 * This is a complete landing page with:
 * - Hero section with CTA
 * - Feature grid
 * - Pricing cards
 * - Testimonials
 * - Footer
 */

import React, { useState } from 'react';

export function LandingPage() {
  const [selectedPlan, setSelectedPlan] = useState<string | null>(null);

  return (
    <div className="min-h-screen bg-white">
      {/* Hero Section */}
      <section className="relative bg-gradient-to-r from-blue-600 to-purple-600 text-white">
        <div className="container mx-auto px-4 py-20">
          <div className="max-w-3xl mx-auto text-center">
            <h1 className="text-5xl font-bold mb-6">
              Build Web Apps Visually
            </h1>
            <p className="text-xl mb-8 text-blue-100">
              Create stunning web applications without writing code.
              Drag, drop, and export production-ready React components.
            </p>
            <div className="flex gap-4 justify-center">
              <button className="bg-white text-blue-600 px-8 py-3 rounded-lg font-semibold hover:bg-blue-50 transition">
                Start Free Trial
              </button>
              <button className="bg-transparent border-2 border-white px-8 py-3 rounded-lg font-semibold hover:bg-white/10 transition">
                View Demo
              </button>
            </div>
          </div>
        </div>
      </section>

      {/* Feature Grid */}
      <section className="py-20">
        <div className="container mx-auto px-4">
          <h2 className="text-3xl font-bold text-center mb-12">
            Everything You Need
          </h2>
          <div className="grid md:grid-cols-3 gap-8">
            {[
              {
                icon: '⚡',
                title: 'Lightning Fast',
                description: 'Build applications in minutes, not days. Our visual builder accelerates your development workflow.'
              },
              {
                icon: '🎨',
                title: 'Beautiful UI',
                description: 'All components use Tailwind CSS and follow modern design best practices out of the box.'
              },
              {
                icon: '📦',
                title: '180+ Components',
                description: 'From simple buttons to complex dashboards, we have every component you need.'
              },
              {
                icon: '🔒',
                title: 'Production Ready',
                description: 'Export clean, typed TypeScript code that\'s ready to deploy to any platform.'
              },
              {
                icon: '🤖',
                title: 'AI Assistant',
                description: 'Built-in AI helps you arrange components and suggests the best layouts for your needs.'
              },
              {
                icon: '📱',
                title: 'Fully Responsive',
                description: 'All components are mobile-first and work perfectly on any device size.'
              }
            ].map((feature, index) => (
              <div key={index} className="bg-white p-6 rounded-lg border border-gray-200 hover:border-blue-500 transition">
                <div className="text-4xl mb-4">{feature.icon}</div>
                <h3 className="text-xl font-semibold mb-2">{feature.title}</h3>
                <p className="text-gray-600">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing Section */}
      <section className="py-20 bg-gray-50">
        <div className="container mx-auto px-4">
          <h2 className="text-3xl font-bold text-center mb-4">
            Simple, Transparent Pricing
          </h2>
          <p className="text-center text-gray-600 mb-12">
            Choose the plan that fits your needs
          </p>

          <div className="grid md:grid-cols-3 gap-8 max-w-5xl mx-auto">
            {[
              {
                name: 'Starter',
                price: '$0',
                period: 'forever',
                features: [
                  '5 projects',
                  'Basic components',
                  'Export to React',
                  'Community support'
                ],
                highlighted: false
              },
              {
                name: 'Pro',
                price: '$29',
                period: 'per month',
                features: [
                  'Unlimited projects',
                  'All 180+ components',
                  'Export to React, Next.js, HTML',
                  'Priority support',
                  'AI Assistant',
                  'Custom themes'
                ],
                highlighted: true
              },
              {
                name: 'Enterprise',
                price: '$99',
                period: 'per month',
                features: [
                  'Everything in Pro',
                  'Team collaboration',
                  'Custom components',
                  'Dedicated support',
                  'SSO integration',
                  'SLA guarantee'
                ],
                highlighted: false
              }
            ].map((plan, index) => (
              <div
                key={index}
                className={`bg-white p-8 rounded-lg border-2 ${
                  plan.highlighted
                    ? 'border-blue-500 shadow-xl scale-105'
                    : 'border-gray-200'
                }`}
              >
                {plan.highlighted && (
                  <div className="bg-blue-500 text-white text-sm font-semibold px-3 py-1 rounded-full inline-block mb-4">
                    Most Popular
                  </div>
                )}
                <h3 className="text-2xl font-bold mb-2">{plan.name}</h3>
                <div className="mb-6">
                  <span className="text-4xl font-bold">{plan.price}</span>
                  <span className="text-gray-600">/{plan.period}</span>
                </div>
                <ul className="space-y-3 mb-8">
                  {plan.features.map((feature, i) => (
                    <li key={i} className="flex items-start gap-2">
                      <span className="text-green-500">✓</span>
                      <span className="text-gray-700">{feature}</span>
                    </li>
                  ))}
                </ul>
                <button
                  onClick={() => setSelectedPlan(plan.name)}
                  className={`w-full py-3 rounded-lg font-semibold transition ${
                    plan.highlighted
                      ? 'bg-blue-500 text-white hover:bg-blue-600'
                      : 'bg-gray-100 text-gray-900 hover:bg-gray-200'
                  }`}
                >
                  Get Started
                </button>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="py-20">
        <div className="container mx-auto px-4">
          <h2 className="text-3xl font-bold text-center mb-12">
            Loved by Developers
          </h2>
          <div className="grid md:grid-cols-3 gap-8 max-w-5xl mx-auto">
            {[
              {
                name: 'Sarah Chen',
                role: 'Frontend Developer',
                avatar: 'SC',
                quote: 'HubLab cut my development time in half. I can build complete landing pages in minutes instead of hours.'
              },
              {
                name: 'Marcus Johnson',
                role: 'Startup Founder',
                avatar: 'MJ',
                quote: 'As a non-technical founder, HubLab lets me prototype ideas quickly and hand off clean code to my team.'
              },
              {
                name: 'Emma Rodriguez',
                role: 'Product Designer',
                avatar: 'ER',
                quote: 'The component library is incredible. Everything just works and looks professional out of the box.'
              }
            ].map((testimonial, index) => (
              <div key={index} className="bg-white p-6 rounded-lg border border-gray-200">
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-12 h-12 bg-blue-500 text-white rounded-full flex items-center justify-center font-semibold">
                    {testimonial.avatar}
                  </div>
                  <div>
                    <div className="font-semibold">{testimonial.name}</div>
                    <div className="text-sm text-gray-600">{testimonial.role}</div>
                  </div>
                </div>
                <p className="text-gray-700 italic">"{testimonial.quote}"</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-blue-600 text-white">
        <div className="container mx-auto px-4 text-center">
          <h2 className="text-4xl font-bold mb-4">
            Ready to Build Something Amazing?
          </h2>
          <p className="text-xl mb-8 text-blue-100">
            Join thousands of developers building faster with HubLab
          </p>
          <button className="bg-white text-blue-600 px-8 py-3 rounded-lg font-semibold hover:bg-blue-50 transition">
            Start Building for Free
          </button>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-gray-900 text-white py-12">
        <div className="container mx-auto px-4">
          <div className="grid md:grid-cols-4 gap-8">
            <div>
              <h3 className="font-bold text-lg mb-4">HubLab</h3>
              <p className="text-gray-400 text-sm">
                Build web applications visually with 180+ production-ready components.
              </p>
            </div>
            <div>
              <h4 className="font-semibold mb-4">Product</h4>
              <ul className="space-y-2 text-sm text-gray-400">
                <li><a href="#" className="hover:text-white">Features</a></li>
                <li><a href="#" className="hover:text-white">Pricing</a></li>
                <li><a href="#" className="hover:text-white">Components</a></li>
                <li><a href="#" className="hover:text-white">Docs</a></li>
              </ul>
            </div>
            <div>
              <h4 className="font-semibold mb-4">Company</h4>
              <ul className="space-y-2 text-sm text-gray-400">
                <li><a href="#" className="hover:text-white">About</a></li>
                <li><a href="#" className="hover:text-white">Blog</a></li>
                <li><a href="#" className="hover:text-white">Careers</a></li>
                <li><a href="#" className="hover:text-white">Contact</a></li>
              </ul>
            </div>
            <div>
              <h4 className="font-semibold mb-4">Legal</h4>
              <ul className="space-y-2 text-sm text-gray-400">
                <li><a href="#" className="hover:text-white">Privacy</a></li>
                <li><a href="#" className="hover:text-white">Terms</a></li>
                <li><a href="#" className="hover:text-white">Security</a></li>
              </ul>
            </div>
          </div>
          <div className="border-t border-gray-800 mt-8 pt-8 text-center text-sm text-gray-400">
            © 2025 HubLab. All rights reserved.
          </div>
        </div>
      </footer>
    </div>
  );
}

export default LandingPage;
