/**
 * Admin Dashboard Page
 * Generated by HubLab Studio V2
 * https://hublab.dev/studio-v2
 *
 * This dashboard includes:
 * - Real-time metrics
 * - Data visualization with charts
 * - User management table
 * - API data fetching with SWR
 */

'use client';

import React, { useState } from 'react';
import useSWR from 'swr';

// Data fetching helper
const fetcher = (url: string) => fetch(url).then((res) => res.json());

interface DashboardStats {
  totalUsers: number;
  revenue: number;
  activeSessions: number;
  conversionRate: number;
}

interface User {
  id: string;
  name: string;
  email: string;
  role: string;
  status: 'active' | 'inactive';
}

interface ChartData {
  month: string;
  value: number;
}

export default function DashboardPage() {
  const [sidebarOpen, setSidebarOpen] = useState(true);
  const [selectedUser, setSelectedUser] = useState<User | null>(null);

  // Fetch dashboard stats
  const { data: stats, error: statsError } = useSWR<DashboardStats>(
    '/api/dashboard/stats',
    fetcher,
    { refreshInterval: 30000 } // Refresh every 30 seconds
  );

  // Fetch users
  const { data: users, error: usersError } = useSWR<User[]>(
    '/api/users',
    fetcher
  );

  // Fetch chart data
  const { data: chartData, error: chartError } = useSWR<ChartData[]>(
    '/api/dashboard/revenue',
    fetcher
  );

  return (
    <div className="flex h-screen bg-gray-100">
      {/* Sidebar */}
      <aside
        className={`bg-gray-900 text-white transition-all duration-300 ${
          sidebarOpen ? 'w-64' : 'w-20'
        }`}
      >
        <div className="p-4 flex items-center justify-between">
          {sidebarOpen && <h1 className="text-xl font-bold">Admin Panel</h1>}
          <button
            onClick={() => setSidebarOpen(!sidebarOpen)}
            className="p-2 hover:bg-gray-800 rounded"
          >
            ☰
          </button>
        </div>

        <nav className="mt-8">
          {[
            { icon: '📊', label: 'Dashboard', href: '/dashboard' },
            { icon: '👥', label: 'Users', href: '/users' },
            { icon: '💰', label: 'Sales', href: '/sales' },
            { icon: '📈', label: 'Analytics', href: '/analytics' },
            { icon: '⚙️', label: 'Settings', href: '/settings' },
          ].map((item, index) => (
            <a
              key={index}
              href={item.href}
              className="flex items-center gap-3 px-4 py-3 hover:bg-gray-800 transition"
            >
              <span className="text-2xl">{item.icon}</span>
              {sidebarOpen && <span>{item.label}</span>}
            </a>
          ))}
        </nav>
      </aside>

      {/* Main Content */}
      <main className="flex-1 overflow-auto">
        <div className="p-8">
          {/* Header */}
          <div className="mb-8">
            <h1 className="text-3xl font-bold text-gray-900 mb-2">
              Dashboard Overview
            </h1>
            <p className="text-gray-600">
              Welcome back! Here's what's happening today.
            </p>
          </div>

          {/* Stats Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
            {statsError ? (
              <div className="col-span-4 bg-red-50 border border-red-200 rounded-lg p-4 text-red-700">
                Error loading stats. Please try again.
              </div>
            ) : !stats ? (
              // Loading skeleton
              Array.from({ length: 4 }).map((_, i) => (
                <div key={i} className="bg-white p-6 rounded-lg border border-gray-200 animate-pulse">
                  <div className="h-4 bg-gray-200 rounded w-1/2 mb-4"></div>
                  <div className="h-8 bg-gray-200 rounded w-3/4"></div>
                </div>
              ))
            ) : (
              [
                {
                  title: 'Total Users',
                  value: stats.totalUsers.toLocaleString(),
                  trend: 12.5,
                  icon: '👥',
                },
                {
                  title: 'Revenue',
                  value: `$${stats.revenue.toLocaleString()}`,
                  trend: 8.3,
                  icon: '💰',
                },
                {
                  title: 'Active Sessions',
                  value: stats.activeSessions.toLocaleString(),
                  trend: -2.1,
                  icon: '🔥',
                },
                {
                  title: 'Conversion Rate',
                  value: `${stats.conversionRate}%`,
                  trend: 5.7,
                  icon: '📈',
                },
              ].map((stat, index) => (
                <div
                  key={index}
                  className="bg-white p-6 rounded-lg border border-gray-200 hover:shadow-lg transition"
                >
                  <div className="flex items-center justify-between mb-4">
                    <span className="text-gray-600 text-sm font-medium">
                      {stat.title}
                    </span>
                    <span className="text-2xl">{stat.icon}</span>
                  </div>
                  <div className="text-3xl font-bold text-gray-900 mb-2">
                    {stat.value}
                  </div>
                  <div
                    className={`text-sm font-medium ${
                      stat.trend > 0 ? 'text-green-600' : 'text-red-600'
                    }`}
                  >
                    {stat.trend > 0 ? '↑' : '↓'} {Math.abs(stat.trend)}% vs last month
                  </div>
                </div>
              ))
            )}
          </div>

          {/* Charts Section */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-8">
            {/* Revenue Chart */}
            <div className="bg-white p-6 rounded-lg border border-gray-200">
              <h3 className="text-lg font-semibold mb-4">Monthly Revenue</h3>
              {chartError ? (
                <div className="text-red-600">Error loading chart data</div>
              ) : !chartData ? (
                <div className="animate-pulse">
                  <div className="h-64 bg-gray-200 rounded"></div>
                </div>
              ) : (
                <div className="h-64 flex items-end gap-2">
                  {chartData.map((item, index) => (
                    <div key={index} className="flex-1 flex flex-col items-center">
                      <div
                        className="w-full bg-blue-500 rounded-t hover:bg-blue-600 transition cursor-pointer"
                        style={{
                          height: `${(item.value / Math.max(...chartData.map(d => d.value))) * 100}%`,
                        }}
                        title={`${item.month}: $${item.value.toLocaleString()}`}
                      ></div>
                      <div className="text-xs text-gray-600 mt-2">{item.month}</div>
                    </div>
                  ))}
                </div>
              )}
            </div>

            {/* User Growth Chart */}
            <div className="bg-white p-6 rounded-lg border border-gray-200">
              <h3 className="text-lg font-semibold mb-4">User Growth</h3>
              <div className="h-64 flex items-end gap-1">
                {[20, 35, 30, 45, 40, 50, 55, 60, 58, 65, 70, 75].map((value, index) => (
                  <div key={index} className="flex-1 flex flex-col items-center">
                    <div
                      className="w-full bg-green-500 rounded-t hover:bg-green-600 transition"
                      style={{ height: `${value}%` }}
                    ></div>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Users Table */}
          <div className="bg-white rounded-lg border border-gray-200">
            <div className="p-6 border-b border-gray-200">
              <div className="flex items-center justify-between">
                <h3 className="text-lg font-semibold">Recent Users</h3>
                <input
                  type="text"
                  placeholder="Search users..."
                  className="px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>
            </div>

            <div className="overflow-x-auto">
              <table className="w-full">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      User
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Email
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Role
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Status
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Actions
                    </th>
                  </tr>
                </thead>
                <tbody className="bg-white divide-y divide-gray-200">
                  {usersError ? (
                    <tr>
                      <td colSpan={5} className="px-6 py-4 text-center text-red-600">
                        Error loading users
                      </td>
                    </tr>
                  ) : !users ? (
                    Array.from({ length: 5 }).map((_, i) => (
                      <tr key={i} className="animate-pulse">
                        <td className="px-6 py-4"><div className="h-4 bg-gray-200 rounded w-32"></div></td>
                        <td className="px-6 py-4"><div className="h-4 bg-gray-200 rounded w-48"></div></td>
                        <td className="px-6 py-4"><div className="h-4 bg-gray-200 rounded w-20"></div></td>
                        <td className="px-6 py-4"><div className="h-4 bg-gray-200 rounded w-16"></div></td>
                        <td className="px-6 py-4"><div className="h-4 bg-gray-200 rounded w-24"></div></td>
                      </tr>
                    ))
                  ) : (
                    users.map((user) => (
                      <tr key={user.id} className="hover:bg-gray-50">
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="flex items-center">
                            <div className="h-10 w-10 rounded-full bg-blue-500 text-white flex items-center justify-center font-semibold">
                              {user.name.charAt(0)}
                            </div>
                            <div className="ml-4">
                              <div className="text-sm font-medium text-gray-900">
                                {user.name}
                              </div>
                            </div>
                          </div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="text-sm text-gray-900">{user.email}</div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <span className="px-2 py-1 inline-flex text-xs leading-5 font-semibold rounded-full bg-blue-100 text-blue-800">
                            {user.role}
                          </span>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <span
                            className={`px-2 py-1 inline-flex text-xs leading-5 font-semibold rounded-full ${
                              user.status === 'active'
                                ? 'bg-green-100 text-green-800'
                                : 'bg-gray-100 text-gray-800'
                            }`}
                          >
                            {user.status}
                          </span>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm font-medium">
                          <button
                            onClick={() => setSelectedUser(user)}
                            className="text-blue-600 hover:text-blue-900 mr-4"
                          >
                            Edit
                          </button>
                          <button className="text-red-600 hover:text-red-900">
                            Delete
                          </button>
                        </td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
