/**
 * Extended Capsules Batch 12 - 300 capsules
 * Data Science, Analytics, Business Intelligence, Visualization
 */

import { Capsule } from '@/types/capsule'

const generateCapsule = (id: string, name: string, category: string, desc: string, tags: string[]): Capsule => ({
  id, name, category, description: desc, tags,
  code: `'use client'\nexport default function ${name.replace(/[^a-zA-Z0-9]/g, '')}() {\n  return <div className="p-4 border rounded-lg shadow">${name}</div>\n}`,
  platform: 'react'
})

const extendedCapsulesBatch12: Capsule[] = [
  // Advanced Data Visualization - 100 capsules
  ...['dataviz-scatter-plot', 'dataviz-bubble-chart', 'dataviz-area-chart', 'dataviz-stacked-area', 'dataviz-streamgraph', 'dataviz-candlestick-chart', 'dataviz-ohlc-chart', 'dataviz-waterfall-chart', 'dataviz-funnel-chart', 'dataviz-pyramid-chart', 'dataviz-treemap', 'dataviz-sunburst-chart', 'dataviz-sankey-diagram', 'dataviz-chord-diagram', 'dataviz-network-graph', 'dataviz-force-directed-graph', 'dataviz-dendrogram', 'dataviz-hierarchical-tree', 'dataviz-circular-packing', 'dataviz-voronoi-diagram', 'dataviz-contour-plot', 'dataviz-density-plot', 'dataviz-violin-plot', 'dataviz-box-plot', 'dataviz-ridgeline-plot', 'dataviz-parallel-coordinates', 'dataviz-radar-chart', 'dataviz-polar-chart', 'dataviz-gauge-chart', 'dataviz-speedometer', 'dataviz-bullet-chart', 'dataviz-sparkline-chart', 'dataviz-small-multiples', 'dataviz-horizon-chart', 'dataviz-calendar-heatmap', 'dataviz-choropleth-map', 'dataviz-flow-map', 'dataviz-cartogram', 'dataviz-dot-map', 'dataviz-hexbin-map', 'dataviz-3d-surface-plot', 'dataviz-3d-scatter', 'dataviz-3d-bar-chart', 'dataviz-mesh-plot', 'dataviz-volume-rendering', 'dataviz-isosurface', 'dataviz-streamline-plot', 'dataviz-vector-field', 'dataviz-word-cloud', 'dataviz-tag-cloud', 'dataviz-circle-packing', 'dataviz-icicle-chart', 'dataviz-flame-graph', 'dataviz-timeline-chart', 'dataviz-gantt-timeline', 'dataviz-swimlane-chart', 'dataviz-alluvial-diagram', 'dataviz-arc-diagram', 'dataviz-matrix-chart', 'dataviz-adjacency-matrix', 'dataviz-hive-plot', 'dataviz-node-link-diagram', 'dataviz-edge-bundling', 'dataviz-radial-tree', 'dataviz-phylogenetic-tree', 'dataviz-layered-graph', 'dataviz-dependency-graph', 'dataviz-state-diagram', 'dataviz-petri-net', 'dataviz-venn-diagram', 'dataviz-euler-diagram', 'dataviz-upset-plot', 'dataviz-marimekko-chart', 'dataviz-mosaic-plot', 'dataviz-slope-chart', 'dataviz-bump-chart', 'dataviz-dumbbell-chart', 'dataviz-lollipop-chart', 'dataviz-dot-plot', 'dataviz-strip-plot', 'dataviz-beeswarm-plot', 'dataviz-joy-plot', 'dataviz-isotype-chart', 'dataviz-pictogram', 'dataviz-waffle-chart', 'dataviz-unit-chart', 'dataviz-step-chart', 'dataviz-range-chart', 'dataviz-span-chart', 'dataviz-threshold-chart', 'dataviz-control-chart', 'dataviz-pareto-chart', 'dataviz-histogram-chart', 'dataviz-frequency-polygon', 'dataviz-ogive-chart', 'dataviz-qq-plot', 'dataviz-pp-plot', 'dataviz-lag-plot', 'dataviz-autocorrelation'].map((id) =>
    generateCapsule(id, id.split('-').slice(1).map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' '), 'DataViz', `${id.split('-').slice(1).join(' ')} data visualization component`, ['dataviz', 'chart', 'visualization'])
  ),

  // Business Intelligence & Analytics - 100 capsules
  ...['bi-dashboard-builder', 'bi-kpi-designer', 'bi-metric-card', 'bi-scorecard', 'bi-balanced-scorecard', 'bi-executive-dashboard', 'bi-operational-dashboard', 'bi-analytical-dashboard', 'bi-strategic-dashboard', 'bi-real-time-dashboard', 'bi-drill-down-report', 'bi-drill-through', 'bi-slice-dice', 'bi-pivot-table', 'bi-cross-tab', 'bi-data-grid', 'bi-aggregation-builder', 'bi-grouping-tool', 'bi-sorting-control', 'bi-filtering-panel', 'bi-search-filter', 'bi-date-range-filter', 'bi-multi-select-filter', 'bi-cascading-filter', 'bi-dynamic-filter', 'bi-saved-filters', 'bi-filter-presets', 'bi-quick-filters', 'bi-global-filters', 'bi-drill-anywhere', 'bi-data-discovery', 'bi-ad-hoc-reporting', 'bi-self-service-bi', 'bi-query-builder-bi', 'bi-visual-query', 'bi-sql-editor-bi', 'bi-data-explorer', 'bi-data-profiling', 'bi-data-quality', 'bi-data-lineage', 'bi-data-catalog', 'bi-metadata-viewer', 'bi-data-dictionary', 'bi-etl-pipeline', 'bi-data-transformation', 'bi-data-cleansing', 'bi-data-enrichment', 'bi-data-blending', 'bi-data-joining', 'bi-data-union', 'bi-calculated-fields', 'bi-measure-builder', 'bi-dimension-builder', 'bi-hierarchy-builder', 'bi-date-hierarchy', 'bi-custom-hierarchy', 'bi-parameter-control', 'bi-what-if-analysis-bi', 'bi-scenario-planning-bi', 'bi-forecast-model', 'bi-trend-analysis', 'bi-variance-analysis', 'bi-correlation-analysis', 'bi-regression-analysis', 'bi-cluster-analysis', 'bi-segmentation-tool', 'bi-cohort-builder', 'bi-funnel-analyzer', 'bi-path-analysis', 'bi-attribution-model', 'bi-conversion-tracking', 'bi-retention-analysis', 'bi-churn-prediction', 'bi-lifetime-value', 'bi-rfm-analysis', 'bi-abc-analysis', 'bi-pareto-analysis-bi', 'bi-benchmarking', 'bi-comparative-analysis', 'bi-yoy-comparison', 'bi-mom-comparison', 'bi-rolling-average', 'bi-moving-total', 'bi-cumulative-sum', 'bi-running-total', 'bi-rank-function', 'bi-percentile-calc', 'bi-quartile-analysis', 'bi-outlier-detection', 'bi-anomaly-detection-bi', 'bi-alert-threshold', 'bi-notification-rule', 'bi-scheduled-report', 'bi-report-subscription', 'bi-export-dashboard', 'bi-pdf-export-bi', 'bi-excel-export-bi', 'bi-powerpoint-export', 'bi-sharing-controls'].map((id) =>
    generateCapsule(id, id.split('-').slice(1).map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' '), 'Dashboard', `${id.split('-').slice(1).join(' ')} business intelligence component`, ['bi', 'analytics', 'reporting'])
  ),

  // Statistical Analysis & Data Science - 100 capsules
  ...['stats-descriptive-stats', 'stats-summary-statistics', 'stats-central-tendency', 'stats-dispersion-measures', 'stats-skewness-kurtosis', 'stats-confidence-interval', 'stats-hypothesis-testing', 'stats-t-test', 'stats-anova-test', 'stats-chi-square-test', 'stats-correlation-test', 'stats-regression-model', 'stats-linear-regression-stats', 'stats-logistic-regression', 'stats-polynomial-regression', 'stats-multiple-regression', 'stats-stepwise-regression', 'stats-ridge-regression', 'stats-lasso-regression', 'stats-elastic-net', 'stats-time-series-analysis', 'stats-seasonal-decomposition', 'stats-moving-average-stats', 'stats-exponential-smoothing', 'stats-arima-model', 'stats-sarima-model', 'stats-prophet-forecast', 'stats-automl-stats', 'stats-feature-engineering', 'stats-feature-selection', 'stats-feature-importance', 'stats-dimensionality-reduction', 'stats-pca-stats', 'stats-tsne-visualization', 'stats-umap-projection', 'stats-clustering-stats', 'stats-kmeans-stats', 'stats-hierarchical-clustering', 'stats-dbscan-clustering', 'stats-classification-stats', 'stats-decision-tree-stats', 'stats-random-forest-stats', 'stats-gradient-boosting', 'stats-xgboost-model', 'stats-svm-stats', 'stats-naive-bayes', 'stats-knn-classifier', 'stats-neural-network-stats', 'stats-deep-learning-stats', 'stats-cnn-model', 'stats-rnn-model', 'stats-lstm-model', 'stats-transformer-model', 'stats-ensemble-methods', 'stats-bagging', 'stats-boosting', 'stats-stacking', 'stats-cross-validation', 'stats-train-test-split', 'stats-kfold-validation', 'stats-stratified-sampling', 'stats-model-evaluation', 'stats-confusion-matrix', 'stats-roc-curve', 'stats-auc-score', 'stats-precision-recall', 'stats-f1-score', 'stats-accuracy-metrics', 'stats-mae-mse', 'stats-rmse-calculator', 'stats-r-squared', 'stats-adjusted-r-squared', 'stats-residual-plot', 'stats-qq-plot-stats', 'stats-leverage-plot', 'stats-influence-plot', 'stats-vif-calculator', 'stats-multicollinearity', 'stats-heteroscedasticity', 'stats-autocorrelation-test', 'stats-normality-test', 'stats-shapiro-wilk', 'stats-kolmogorov-smirnov', 'stats-anderson-darling', 'stats-jarque-bera', 'stats-box-cox-transform', 'stats-log-transform', 'stats-standardization', 'stats-normalization', 'stats-min-max-scaler', 'stats-robust-scaler', 'stats-one-hot-encoding', 'stats-label-encoding', 'stats-ordinal-encoding', 'stats-target-encoding', 'stats-missing-data-handler', 'stats-imputation-methods', 'stats-outlier-removal', 'stats-winsorization'].map((id) =>
    generateCapsule(id, id.split('-').slice(1).map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' '), 'AI', `${id.split('-').slice(1).join(' ')} statistical analysis component`, ['statistics', 'data-science', 'ml'])
  )
]

export default extendedCapsulesBatch12
