/**
 * Extended Capsules Batch 13 - 300 capsules
 * Design Tools, Creative Suite, Graphics, Typography
 */

import { Capsule } from '@/types/capsule'

const generateCapsule = (id: string, name: string, category: string, desc: string, tags: string[]): Capsule => ({
  id, name, category, description: desc, tags,
  code: `'use client'\nexport default function ${name.replace(/[^a-zA-Z0-9]/g, '')}() {\n  return <div className="p-4 border rounded-lg shadow">${name}</div>\n}`,
  platform: 'react'
})

const extendedCapsulesBatch13: Capsule[] = [
  // Design & Creative Tools - 100 capsules
  ...['design-layer-panel', 'design-artboard-manager', 'design-page-manager', 'design-canvas-infinite', 'design-zoom-pan-design', 'design-ruler-guides', 'design-grid-overlay-design', 'design-snap-to-grid', 'design-snap-to-guides', 'design-snap-to-objects', 'design-alignment-tools', 'design-distribute-objects', 'design-group-objects', 'design-ungroup-objects', 'design-lock-unlock', 'design-hide-show', 'design-opacity-slider', 'design-blend-modes', 'design-layer-effects', 'design-drop-shadow-design', 'design-inner-shadow', 'design-outer-glow', 'design-inner-glow', 'design-bevel-emboss', 'design-gradient-overlay-design', 'design-pattern-overlay', 'design-stroke-effect', 'design-color-overlay-design', 'design-smart-objects', 'design-linked-assets', 'design-component-library', 'design-design-system', 'design-style-guide', 'design-brand-kit', 'design-asset-manager-design', 'design-version-control-design', 'design-revision-history-design', 'design-comment-annotations', 'design-feedback-mode', 'design-approval-workflow-design', 'design-handoff-specs', 'design-developer-mode', 'design-code-export-design', 'design-css-export', 'design-svg-export-design', 'design-inspect-mode', 'design-measure-tool', 'design-color-picker-design', 'design-eyedropper-design', 'design-swatch-library', 'design-gradient-editor-design', 'design-pattern-creator', 'design-texture-library', 'design-brush-library', 'design-shape-library', 'design-icon-library', 'design-template-library-design', 'design-mockup-generator', 'design-wireframe-kit', 'design-prototype-mode', 'design-interactive-prototype', 'design-hotspot-tool', 'design-transition-builder', 'design-animation-timeline', 'design-easing-editor', 'design-keyframe-animation-design', 'design-auto-animate', 'design-scroll-animation', 'design-parallax-effect', 'design-hover-states', 'design-active-states', 'design-disabled-states', 'design-component-variants', 'design-boolean-operations', 'design-path-operations', 'design-vector-editing', 'design-pen-tool-design', 'design-bezier-curves', 'design-anchor-points', 'design-path-smoothing', 'design-outline-stroke', 'design-fill-color', 'design-stroke-width', 'design-dash-pattern', 'design-line-cap', 'design-line-join', 'design-corner-radius', 'design-individual-corners', 'design-transform-tool-design', 'design-rotate-tool', 'design-scale-tool', 'design-skew-tool', 'design-flip-horizontal', 'design-flip-vertical', 'design-constraints-layout', 'design-auto-layout', 'design-responsive-resize', 'design-breakpoint-manager', 'design-device-frames'].map((id) =>
    generateCapsule(id, id.split('-').slice(1).map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' '), 'UI', `${id.split('-').slice(1).join(' ')} design tool component`, ['design', 'creative', 'tools'])
  ),

  // Typography & Text - 100 capsules
  ...['typo-font-selector', 'typo-google-fonts', 'typo-adobe-fonts', 'typo-custom-fonts', 'typo-font-weight', 'typo-font-style', 'typo-font-size', 'typo-line-height', 'typo-letter-spacing', 'typo-word-spacing', 'typo-text-transform', 'typo-text-decoration', 'typo-text-align', 'typo-vertical-align', 'typo-text-indent', 'typo-text-overflow', 'typo-white-space', 'typo-word-wrap', 'typo-word-break', 'typo-hyphens', 'typo-text-shadow', 'typo-text-stroke', 'typo-text-fill', 'typo-gradient-text', 'typo-multicolor-text', 'typo-outlined-text', 'typo-3d-text', 'typo-text-effects', 'typo-curved-text', 'typo-circular-text', 'typo-path-text', 'typo-warped-text', 'typo-distorted-text', 'typo-perspective-text', 'typo-neon-text', 'typo-glitch-text', 'typo-retro-text', 'typo-vintage-text', 'typo-grunge-text', 'typo-handwritten-text', 'typo-calligraphy', 'typo-script-fonts', 'typo-serif-fonts', 'typo-sans-serif', 'typo-monospace-fonts', 'typo-display-fonts', 'typo-decorative-fonts', 'typo-handlettering', 'typo-typography-scale', 'typo-modular-scale', 'typo-type-hierarchy', 'typo-heading-styles', 'typo-body-styles', 'typo-caption-styles', 'typo-quote-styles', 'typo-code-styles', 'typo-list-styles', 'typo-link-styles', 'typo-button-text', 'typo-form-text', 'typo-table-text', 'typo-responsive-text', 'typo-fluid-typography', 'typo-variable-fonts', 'typo-font-features', 'typo-opentype-features', 'typo-ligatures', 'typo-small-caps', 'typo-subscript-superscript', 'typo-fractions', 'typo-ordinals', 'typo-tabular-figures', 'typo-oldstyle-figures', 'typo-slashed-zero', 'typo-kerning-pairs', 'typo-tracking-adjustment', 'typo-baseline-grid', 'typo-vertical-rhythm', 'typo-line-length', 'typo-measure', 'typo-column-width', 'typo-gutter-width', 'typo-multi-column', 'typo-masonry-text', 'typo-drop-cap', 'typo-initial-letter', 'typo-pull-quote', 'typo-block-quote', 'typo-inline-quote', 'typo-citation', 'typo-footnote', 'typo-endnote', 'typo-sidenote', 'typo-margin-note', 'typo-tooltip-text', 'typo-text-selection', 'typo-highlight-color', 'typo-mark-element'].map((id) =>
    generateCapsule(id, id.split('-').slice(1).map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' '), 'UI', `${id.split('-').slice(1).join(' ')} typography component`, ['typography', 'text', 'fonts'])
  ),

  // Image & Graphics Editing - 100 capsules
  ...['graphics-photo-editor', 'graphics-image-filters', 'graphics-instagram-filters', 'graphics-vsco-filters', 'graphics-vintage-filter', 'graphics-black-white', 'graphics-sepia-tone', 'graphics-duotone', 'graphics-tritone', 'graphics-split-tone', 'graphics-color-pop', 'graphics-selective-color', 'graphics-hsl-adjustment', 'graphics-curves-adjustment', 'graphics-levels-adjustment', 'graphics-exposure-graphics', 'graphics-highlights-shadows', 'graphics-whites-blacks', 'graphics-vibrance-saturation', 'graphics-temperature-tint', 'graphics-clarity-dehaze', 'graphics-vignette-graphics', 'graphics-grain-graphics', 'graphics-fade-effect', 'graphics-sharpen-graphics', 'graphics-noise-reduction', 'graphics-chromatic-aberration-graphics', 'graphics-lens-correction', 'graphics-distortion-correction', 'graphics-perspective-correction', 'graphics-tilt-shift', 'graphics-miniature-effect', 'graphics-bokeh-effect', 'graphics-depth-of-field-graphics', 'graphics-motion-blur', 'graphics-radial-blur', 'graphics-zoom-blur', 'graphics-gaussian-blur', 'graphics-surface-blur', 'graphics-smart-blur', 'graphics-oil-painting', 'graphics-watercolor', 'graphics-sketch-effect', 'graphics-cartoon-effect', 'graphics-comic-effect', 'graphics-halftone', 'graphics-posterize-graphics', 'graphics-solarize', 'graphics-invert-colors', 'graphics-threshold-graphics', 'graphics-pixelate', 'graphics-mosaic', 'graphics-crystallize', 'graphics-pointillize', 'graphics-emboss-graphics', 'graphics-find-edges', 'graphics-glowing-edges', 'graphics-neon-glow', 'graphics-soft-glow', 'graphics-diffuse-glow', 'graphics-outer-glow-graphics', 'graphics-inner-glow-graphics', 'graphics-lens-flare-graphics', 'graphics-lighting-effects', 'graphics-cloud-filter', 'graphics-fiber-texture', 'graphics-noise-texture', 'graphics-remove-background', 'graphics-background-eraser', 'graphics-magic-wand-graphics', 'graphics-quick-selection', 'graphics-object-selection', 'graphics-subject-select', 'graphics-hair-refinement', 'graphics-edge-refinement', 'graphics-feather-selection', 'graphics-expand-contract', 'graphics-inverse-selection', 'graphics-layer-mask', 'graphics-vector-mask', 'graphics-clipping-mask', 'graphics-alpha-channel', 'graphics-transparency-graphics', 'graphics-blend-if', 'graphics-knockout', 'graphics-liquify-tool', 'graphics-warp-transform', 'graphics-puppet-warp', 'graphics-content-aware-fill', 'graphics-content-aware-scale', 'graphics-patch-tool', 'graphics-healing-brush', 'graphics-clone-stamp', 'graphics-spot-healing', 'graphics-red-eye-removal', 'graphics-blemish-remover', 'graphics-teeth-whitening', 'graphics-skin-smoothing', 'graphics-face-retouching'].map((id) =>
    generateCapsule(id, id.split('-').slice(1).map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' '), 'Media', `${id.split('-').slice(1).join(' ')} graphics editing component`, ['graphics', 'image', 'editing'])
  )
]

export default extendedCapsulesBatch13
