/**
 * Extended Capsules Batch 16 - 300 capsules
 * Content Management, Publishing, Digital Asset Management
 */

import { Capsule } from '@/types/capsule'

const generateCapsule = (id: string, name: string, category: string, desc: string, tags: string[]): Capsule => ({
  id, name, category, description: desc, tags,
  code: `'use client'\nexport default function ${name.replace(/[^a-zA-Z0-9]/g, '')}() {\n  return <div className="p-4 border rounded-lg shadow">${name}</div>\n}`,
  platform: 'react'
})

const extendedCapsulesBatch16: Capsule[] = [
  // Content Management System - 100 capsules
  ...['cms-content-editor', 'cms-wysiwyg-editor', 'cms-markdown-editor', 'cms-block-editor', 'cms-page-builder', 'cms-drag-drop-builder', 'cms-component-library-cms', 'cms-content-blocks', 'cms-reusable-sections', 'cms-layout-templates', 'cms-page-templates', 'cms-content-types', 'cms-custom-fields', 'cms-field-builder', 'cms-relationship-fields', 'cms-media-picker', 'cms-image-selector', 'cms-gallery-builder', 'cms-video-embedder', 'cms-file-browser', 'cms-asset-uploader', 'cms-bulk-upload', 'cms-drag-drop-upload', 'cms-url-import', 'cms-content-preview', 'cms-responsive-preview', 'cms-device-simulator', 'cms-live-preview', 'cms-draft-mode', 'cms-autosave', 'cms-version-history-cms', 'cms-revision-comparison', 'cms-rollback-version', 'cms-content-scheduling', 'cms-publish-schedule', 'cms-unpublish-schedule', 'cms-content-calendar', 'cms-editorial-calendar', 'cms-workflow-builder-cms', 'cms-approval-workflow-cms', 'cms-content-review', 'cms-multi-stage-approval', 'cms-reviewer-assignment', 'cms-comment-system-cms', 'cms-inline-comments', 'cms-suggestion-mode-cms', 'cms-change-tracking', 'cms-content-diff', 'cms-taxonomy-manager', 'cms-category-tree', 'cms-tag-manager', 'cms-tag-autocomplete', 'cms-metadata-editor', 'cms-seo-fields', 'cms-og-tags-editor', 'cms-twitter-cards', 'cms-schema-markup', 'cms-breadcrumb-builder', 'cms-url-slug-generator', 'cms-redirect-manager', 'cms-301-redirects', 'cms-404-monitor', 'cms-broken-link-checker', 'cms-sitemap-generator', 'cms-robots-txt-editor', 'cms-content-search', 'cms-global-search', 'cms-advanced-filters', 'cms-saved-searches', 'cms-content-analytics', 'cms-page-views', 'cms-engagement-metrics', 'cms-content-performance', 'cms-popular-content', 'cms-trending-topics', 'cms-content-gaps', 'cms-user-roles-cms', 'cms-permission-manager', 'cms-access-control', 'cms-content-permissions', 'cms-team-collaboration', 'cms-user-activity-log', 'cms-audit-trail-cms', 'cms-content-history', 'cms-multi-language', 'cms-translation-manager', 'cms-locale-switcher', 'cms-rtl-support', 'cms-content-variants', 'cms-ab-testing-cms', 'cms-personalization', 'cms-audience-targeting', 'cms-geo-targeting-cms', 'cms-device-targeting', 'cms-time-based-content', 'cms-api-explorer', 'cms-graphql-playground', 'cms-rest-api-docs', 'cms-webhook-manager-cms'].map((id) =>
    generateCapsule(id, id.split('-').slice(1).map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' '), 'UI', `${id.split('-').slice(1).join(' ')} CMS component`, ['cms', 'content', 'publishing'])
  ),

  // Digital Asset Management - 100 capsules
  ...['dam-asset-library', 'dam-media-grid', 'dam-list-view', 'dam-thumbnail-view', 'dam-detail-view', 'dam-asset-preview', 'dam-image-viewer', 'dam-video-player-dam', 'dam-audio-player-dam', 'dam-document-viewer', 'dam-pdf-viewer', 'dam-3d-model-viewer', 'dam-asset-upload', 'dam-drag-drop-zone', 'dam-bulk-upload-dam', 'dam-ftp-import', 'dam-cloud-import', 'dam-url-import-dam', 'dam-folder-structure', 'dam-collection-manager', 'dam-smart-collections', 'dam-dynamic-collections', 'dam-asset-tagging', 'dam-auto-tagging', 'dam-ai-tagging', 'dam-facial-recognition-dam', 'dam-object-detection-dam', 'dam-color-detection', 'dam-dominant-colors', 'dam-color-palette-extractor', 'dam-metadata-extraction', 'dam-exif-reader', 'dam-iptc-data', 'dam-xmp-metadata', 'dam-custom-metadata', 'dam-metadata-templates', 'dam-batch-metadata', 'dam-metadata-mapping', 'dam-search-assets', 'dam-faceted-search', 'dam-visual-search', 'dam-reverse-image-search', 'dam-similarity-search', 'dam-advanced-filters-dam', 'dam-saved-filters', 'dam-filter-presets', 'dam-asset-versions', 'dam-version-control-dam', 'dam-version-comparison', 'dam-image-editor-dam', 'dam-crop-tool', 'dam-resize-tool', 'dam-rotate-flip', 'dam-filters-adjustments', 'dam-color-correction', 'dam-brightness-contrast', 'dam-saturation-hue', 'dam-sharpness-blur', 'dam-text-overlay-dam', 'dam-watermark-tool', 'dam-batch-processing', 'dam-image-optimization', 'dam-format-conversion', 'dam-responsive-images', 'dam-cdn-integration', 'dam-delivery-urls', 'dam-transform-urls', 'dam-renditions-manager', 'dam-preset-renditions', 'dam-on-demand-renditions', 'dam-usage-tracking', 'dam-asset-analytics', 'dam-download-stats', 'dam-view-count', 'dam-expiration-manager', 'dam-license-tracking', 'dam-rights-management', 'dam-usage-rights', 'dam-copyright-info', 'dam-model-release', 'dam-property-release', 'dam-approval-process', 'dam-review-workflow', 'dam-asset-sharing', 'dam-share-links', 'dam-embed-codes', 'dam-lightbox-creator', 'dam-portfolio-builder', 'dam-brand-portal', 'dam-asset-export', 'dam-batch-download', 'dam-zip-archive', 'dam-print-ordering', 'dam-storage-analytics', 'dam-quota-monitor', 'dam-duplicate-finder', 'dam-orphan-detector', 'dam-backup-manager', 'dam-disaster-recovery'].map((id) =>
    generateCapsule(id, id.split('-').slice(1).map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' '), 'Media', `${id.split('-').slice(1).join(' ')} DAM component`, ['dam', 'assets', 'media-library'])
  ),

  // Publishing & Editorial - 100 capsules
  ...['publish-newsroom-dashboard', 'publish-story-editor', 'publish-article-composer', 'publish-headline-analyzer', 'publish-headline-optimizer', 'publish-subhead-suggestions', 'publish-lead-paragraph', 'publish-inverted-pyramid', 'publish-story-structure', 'publish-paragraph-editor', 'publish-sentence-analyzer', 'publish-readability-score', 'publish-flesch-reading-ease', 'publish-grade-level', 'publish-word-count', 'publish-character-count', 'publish-reading-time', 'publish-byline-editor', 'publish-author-bio', 'publish-contributor-manager', 'publish-columnist-profiles', 'publish-dateline-generator', 'publish-location-tagger', 'publish-fact-checker', 'publish-source-verification', 'publish-citation-manager', 'publish-reference-links', 'publish-hyperlink-manager', 'publish-internal-linking', 'publish-related-articles', 'publish-story-packages', 'publish-series-manager', 'publish-newsletter-builder', 'publish-newsletter-templates', 'publish-email-preview', 'publish-subscriber-segments', 'publish-distribution-list', 'publish-send-schedule', 'publish-breaking-news-alert', 'publish-push-notification-pub', 'publish-notification-composer', 'publish-alert-scheduler', 'publish-social-share-pub', 'publish-tweet-composer', 'publish-thread-builder', 'publish-facebook-post', 'publish-instagram-caption', 'publish-linkedin-post', 'publish-social-scheduler-pub', 'publish-multi-channel-pub', 'publish-crosspost-manager', 'publish-embargo-manager', 'publish-hold-for-release', 'publish-timed-publication', 'publish-geo-restriction', 'publish-paywall-settings', 'publish-metered-access', 'publish-subscriber-only', 'publish-premium-content', 'publish-sponsored-content', 'publish-native-advertising', 'publish-advertorial-marker', 'publish-disclosure-notice', 'publish-correction-append', 'publish-update-notice', 'publish-editor-note', 'publish-retraction-notice', 'publish-print-layout', 'publish-page-designer', 'publish-grid-layout-pub', 'publish-column-layout', 'publish-page-pagination', 'publish-section-manager', 'publish-front-page-layout', 'publish-edition-manager', 'publish-print-queue', 'publish-press-time', 'publish-circulation-data', 'publish-subscriber-count', 'publish-engagement-metrics-pub', 'publish-article-performance', 'publish-traffic-analytics', 'publish-conversion-tracking-pub', 'publish-subscription-funnel', 'publish-paywall-conversion', 'publish-reader-comments', 'publish-comment-moderation', 'publish-community-guidelines', 'publish-user-reports', 'publish-content-flagging', 'publish-toxic-comment-filter', 'publish-editorial-standards', 'publish-style-guide-pub', 'publish-ap-style-checker', 'publish-house-style', 'publish-glossary-terms', 'publish-acronym-expander'].map((id) =>
    generateCapsule(id, id.split('-').slice(1).map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' '), 'UI', `${id.split('-').slice(1).join(' ')} publishing component`, ['publishing', 'editorial', 'journalism'])
  )
]

export default extendedCapsulesBatch16
