/**
 * Extended Capsules Batch 10 - 250 capsules
 * Video Production, Streaming, Broadcasting, Live Events
 */

import { Capsule } from '@/types/capsule'

const generateCapsule = (id: string, name: string, category: string, desc: string, tags: string[]): Capsule => ({
  id, name, category, description: desc, tags,
  code: `'use client'\nexport default function ${name.replace(/[^a-zA-Z0-9]/g, '')}() {\n  return <div className="p-4 border rounded-lg shadow">${name}</div>\n}`,
  platform: 'react'
})

const extendedCapsulesBatch10: Capsule[] = [
  // Video Production & Editing - 70 capsules
  ...['video-editor-timeline', 'video-multi-track-editor', 'video-trim-tool', 'video-split-tool', 'video-merge-clips', 'video-crop-video', 'video-rotate-video', 'video-flip-video', 'video-speed-control-editor', 'video-reverse-video', 'video-slow-motion', 'video-time-lapse', 'video-freeze-frame', 'video-keyframe-editor', 'video-transition-library', 'video-fade-transition', 'video-wipe-transition', 'video-slide-transition', 'video-zoom-transition', 'video-custom-transitions', 'video-effect-library', 'video-color-grading', 'video-lut-filter', 'video-brightness-contrast-video', 'video-saturation-hue', 'video-exposure-control', 'video-white-balance', 'video-vignette-effect', 'video-grain-effect', 'video-chromatic-aberration', 'video-lens-flare', 'video-glow-effect', 'video-blur-effect-video', 'video-sharpen-effect', 'video-stabilization', 'video-denoise', 'video-green-screen', 'video-chroma-key', 'video-background-removal', 'video-mask-editor', 'video-rotoscoping', 'video-motion-tracking', 'video-object-tracking', 'video-face-tracking-video', 'video-auto-reframe', 'video-smart-crop', 'video-title-generator', 'video-text-overlay', 'video-subtitle-editor', 'video-caption-sync', 'video-subtitle-styles', 'video-lower-third', 'video-name-tag', 'video-ticker-tape', 'video-watermark-overlay', 'video-logo-placement', 'video-end-screen', 'video-intro-template', 'video-outro-template', 'video-thumbnail-generator', 'video-frame-export', 'video-gif-maker', 'video-video-to-audio', 'video-audio-extraction', 'video-audio-sync', 'video-volume-normalization', 'video-audio-ducking', 'video-voiceover-recorder', 'video-noise-reduction-video', 'video-export-presets'].map((id) =>
    generateCapsule(id, id.split('-').slice(1).map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' '), 'Media', `${id.split('-').slice(1).join(' ')} video editing component`, ['video', 'editing', 'production'])
  ),

  // Live Streaming & Broadcasting - 60 capsules
  ...['stream-live-studio', 'stream-control-room', 'stream-scene-switcher', 'stream-source-manager', 'stream-camera-input', 'stream-screen-capture-stream', 'stream-window-capture', 'stream-game-capture', 'stream-virtual-camera', 'stream-obs-integration', 'stream-multi-cam-setup', 'stream-camera-switcher', 'stream-picture-in-picture', 'stream-split-screen-stream', 'stream-overlay-manager', 'stream-alert-system-stream', 'stream-donation-alerts', 'stream-subscriber-alerts', 'stream-follower-alerts', 'stream-chat-overlay', 'stream-emote-display', 'stream-goal-tracker-stream', 'stream-donation-goal', 'stream-subscriber-goal', 'stream-timer-overlay', 'stream-countdown-overlay', 'stream-scoreboard', 'stream-ticker-overlay', 'stream-news-crawler', 'stream-weather-widget', 'stream-social-media-feed', 'stream-twitter-feed-stream', 'stream-poll-overlay', 'stream-voting-system-stream', 'stream-interactive-buttons', 'stream-channel-points', 'stream-prediction-system', 'stream-raffle-system', 'stream-giveaway-manager', 'stream-moderator-tools', 'stream-chat-commands', 'stream-auto-moderation', 'stream-banned-words', 'stream-timeout-system', 'stream-slow-mode', 'stream-subscriber-only', 'stream-emote-only-mode', 'stream-clip-creator', 'stream-highlight-marker', 'stream-vod-manager', 'stream-stream-recorder', 'stream-multi-platform-stream', 'stream-restream-setup', 'stream-rtmp-output', 'stream-srt-output', 'stream-webrtc-output', 'stream-bitrate-control', 'stream-quality-selector', 'stream-encoding-settings', 'stream-bandwidth-monitor', 'stream-health-indicator'].map((id) =>
    generateCapsule(id, id.split('-').slice(1).map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' '), 'Media', `${id.split('-').slice(1).join(' ')} streaming component`, ['streaming', 'live', 'broadcast'])
  ),

  // Video Player & Playback - 60 capsules
  ...['player-video-controls', 'player-play-pause-button', 'player-progress-bar-player', 'player-timeline-scrubber', 'player-volume-control-player', 'player-mute-button', 'player-fullscreen-toggle', 'player-picture-in-picture-player', 'player-playback-speed', 'player-quality-selector-player', 'player-resolution-switcher', 'player-adaptive-bitrate', 'player-auto-quality', 'player-subtitle-toggle', 'player-subtitle-selector', 'player-audio-track-selector', 'player-chapter-markers', 'player-chapter-navigation-player', 'player-thumbnail-preview', 'player-seek-preview', 'player-keyboard-shortcuts-player', 'player-gesture-controls', 'player-double-tap-seek', 'player-swipe-volume', 'player-pinch-zoom-player', 'player-rotate-lock', 'player-autoplay-toggle', 'player-loop-toggle', 'player-playlist-player', 'player-next-video', 'player-previous-video', 'player-shuffle-playlist', 'player-repeat-playlist', 'player-mini-player', 'player-floating-player', 'player-theater-mode', 'player-cinema-mode', 'player-ambient-mode', 'player-casting-button', 'player-chromecast', 'player-airplay', 'player-dlna', 'player-share-button-player', 'player-embed-code', 'player-download-button', 'player-report-issue', 'player-playback-stats', 'player-buffer-indicator', 'player-loading-spinner-player', 'player-error-screen', 'player-retry-button', 'player-annotations', 'player-cards-overlay', 'player-end-screen-player', 'player-related-videos', 'player-up-next', 'player-auto-advance', 'player-watch-later', 'player-add-to-playlist-player', 'player-like-dislike'].map((id) =>
    generateCapsule(id, id.split('-').slice(1).map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' '), 'Media', `${id.split('-').slice(1).join(' ')} video player component`, ['player', 'video', 'playback'])
  ),

  // Live Events & Webinars - 60 capsules
  ...['event-landing-page', 'event-registration-form', 'event-ticketing-system', 'event-payment-gateway-event', 'event-virtual-ticket', 'event-qr-code-ticket', 'event-check-in-system', 'event-attendee-list', 'event-guest-management', 'event-vip-access', 'event-backstage-pass', 'event-lobby-waiting-room', 'event-countdown-timer-event', 'event-live-stage', 'event-main-session', 'event-breakout-sessions', 'event-parallel-tracks', 'event-session-scheduler', 'event-agenda-builder', 'event-speaker-lineup', 'event-speaker-profile-event', 'event-moderator-panel', 'event-panel-discussion', 'event-qa-session', 'event-raise-hand', 'event-audience-questions', 'event-live-polling-event', 'event-survey-event', 'event-feedback-form-event', 'event-interactive-quiz-event', 'event-gamification-event', 'event-leaderboard-event', 'event-prize-draw', 'event-networking-lounge', 'event-virtual-booths', 'event-expo-hall', 'event-sponsor-showcase', 'event-resource-downloads', 'event-slide-deck-viewer', 'event-presentation-sync', 'event-screen-share-event', 'event-whiteboard-event', 'event-collaborative-notes', 'event-live-transcription', 'event-translation-service', 'event-multi-language-support', 'event-closed-captions-event', 'event-sign-language', 'event-accessibility-features', 'event-virtual-background-event', 'event-green-room', 'event-producer-controls', 'event-director-view', 'event-tech-check', 'event-rehearsal-mode', 'event-recording-controls-event', 'event-stream-to-social', 'event-simulcast', 'event-watch-party', 'event-replay-on-demand'].map((id) =>
    generateCapsule(id, id.split('-').slice(1).map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' '), 'Social', `${id.split('-').slice(1).join(' ')} live event component`, ['event', 'webinar', 'conference'])
  )
]

export default extendedCapsulesBatch10
