/**
 * Extended Capsules Batch 1 - 200 capsules
 * Analytics, Maps, Real-time, Security categories
 */

import { Capsule } from '@/types/capsule'

// Helper function to generate capsules
const generateCapsule = (id: string, name: string, category: string, desc: string, tags: string[]): Capsule => ({
  id,
  name,
  category,
  description: desc,
  tags,
  code: `'use client'\nexport default function ${name.replace(/[^a-zA-Z0-9]/g, '')}() {\n  return <div className="p-4 border rounded-lg">${name}</div>\n}`,
  platform: 'react'
})

const extendedCapsulesBatch1: Capsule[] = [
  // Analytics - 50 capsules
  ...Array.from({ length: 50 }, (_, i) => {
    const analytics = [
      ['analytics-dashboard', 'Analytics Dashboard', 'Real-time analytics dashboard with KPIs and metrics'],
      ['analytics-funnel', 'Funnel Analysis', 'Conversion funnel visualization and optimization'],
      ['analytics-cohort', 'Cohort Analysis', 'User cohort segmentation and retention analysis'],
      ['analytics-retention', 'Retention Curves', 'Customer retention and churn analysis'],
      ['analytics-revenue', 'Revenue Analytics', 'Revenue tracking and forecasting'],
      ['analytics-user-journey', 'User Journey Map', 'Visualize user paths and touchpoints'],
      ['analytics-ab-test', 'A/B Test Results', 'Statistical analysis of A/B experiments'],
      ['analytics-heatmap', 'Click Heatmap', 'User interaction heatmaps and click tracking'],
      ['analytics-session-replay', 'Session Replay', 'Record and replay user sessions'],
      ['analytics-event-tracking', 'Event Tracking', 'Custom event tracking and analytics'],
      ['analytics-attribution', 'Attribution Model', 'Multi-touch attribution modeling'],
      ['analytics-ltv', 'LTV Calculator', 'Customer lifetime value calculation'],
      ['analytics-churn-prediction', 'Churn Prediction', 'ML-based churn risk scoring'],
      ['analytics-segment', 'User Segmentation', 'Dynamic user segment creation'],
      ['analytics-metrics', 'Metrics Explorer', 'Explore and analyze custom metrics'],
      ['analytics-report-builder', 'Report Builder', 'Build custom analytics reports'],
      ['analytics-export', 'Data Export', 'Export analytics data to CSV/Excel'],
      ['analytics-schedule-report', 'Scheduled Reports', 'Automated report generation and delivery'],
      ['analytics-real-time', 'Real-time Analytics', 'Live data streaming and visualization'],
      ['analytics-historical', 'Historical Analysis', 'Time-based trend analysis'],
      ['analytics-forecasting', 'Predictive Analytics', 'ML-based forecasting'],
      ['analytics-anomaly', 'Anomaly Detection', 'Detect unusual patterns in metrics'],
      ['analytics-comparison', 'Period Comparison', 'Compare metrics across time periods'],
      ['analytics-benchmark', 'Benchmarking', 'Compare against industry benchmarks'],
      ['analytics-goal-tracking', 'Goal Tracking', 'Track progress towards business goals'],
      ['analytics-kpi', 'KPI Dashboard', 'Key performance indicators monitoring'],
      ['analytics-scorecard', 'Scorecard', 'Balanced scorecard implementation'],
      ['analytics-pivot-table', 'Pivot Table', 'Interactive pivot tables for data analysis'],
      ['analytics-drill-down', 'Drill-down Analysis', 'Hierarchical data exploration'],
      ['analytics-cross-tab', 'Cross Tabulation', 'Cross-tab analysis and reporting'],
      ['analytics-distribution', 'Distribution Analysis', 'Statistical distribution analysis'],
      ['analytics-correlation', 'Correlation Matrix', 'Analyze correlations between metrics'],
      ['analytics-time-series', 'Time Series Analysis', 'Advanced time series analytics'],
      ['analytics-seasonal', 'Seasonality Analysis', 'Detect seasonal patterns'],
      ['analytics-trend', 'Trend Detection', 'Identify and project trends'],
      ['analytics-sentiment', 'Sentiment Analysis', 'Analyze customer sentiment from feedback'],
      ['analytics-nps', 'NPS Calculator', 'Net Promoter Score calculation'],
      ['analytics-csat', 'CSAT Tracker', 'Customer satisfaction tracking'],
      ['analytics-product', 'Product Analytics', 'Feature usage and adoption metrics'],
      ['analytics-mobile', 'Mobile Analytics', 'Mobile app analytics and tracking'],
      ['analytics-web', 'Web Analytics', 'Website traffic and behavior analysis'],
      ['analytics-social', 'Social Analytics', 'Social media metrics and engagement'],
      ['analytics-campaign', 'Campaign Analytics', 'Marketing campaign performance'],
      ['analytics-email', 'Email Analytics', 'Email campaign metrics and engagement'],
      ['analytics-conversion', 'Conversion Tracking', 'Track and optimize conversions'],
      ['analytics-basket', 'Market Basket', 'Basket analysis for recommendations'],
      ['analytics-geo', 'Geographic Analytics', 'Location-based analytics'],
      ['analytics-device', 'Device Analytics', 'Cross-device usage analysis'],
      ['analytics-browser', 'Browser Analytics', 'Browser and platform analytics'],
      ['analytics-performance', 'Performance Analytics', 'App performance monitoring']
    ]
    const [id, name, desc] = analytics[i] || analytics[0]
    return generateCapsule(id, name, 'Dashboard', desc, ['analytics', 'metrics', 'data'])
  }),

  // Maps & GIS - 50 capsules
  ...Array.from({ length: 50 }, (_, i) => {
    const maps = [
      ['map-interactive', 'Interactive Map', 'Fully interactive map with zoom and pan'],
      ['map-marker', 'Map Markers', 'Add custom markers and pins to maps'],
      ['map-cluster', 'Marker Clustering', 'Cluster nearby markers for better performance'],
      ['map-heatmap', 'Heat Map', 'Density heatmap visualization on maps'],
      ['map-route', 'Route Planning', 'Calculate and display routes between points'],
      ['map-directions', 'Turn-by-Turn Directions', 'Navigation with step-by-step directions'],
      ['map-geofence', 'Geofencing', 'Define and monitor geographic boundaries'],
      ['map-distance', 'Distance Calculator', 'Measure distances between locations'],
      ['map-elevation', 'Elevation Profile', 'Show elevation changes along routes'],
      ['map-satellite', 'Satellite View', 'Satellite imagery and terrain maps'],
      ['map-3d', '3D Map View', '3D buildings and terrain visualization'],
      ['map-street-view', 'Street View', 'Immersive street-level imagery'],
      ['map-indoor', 'Indoor Maps', 'Indoor floor plans and navigation'],
      ['map-traffic', 'Live Traffic', 'Real-time traffic conditions overlay'],
      ['map-transit', 'Public Transit', 'Transit routes and schedules'],
      ['map-geocoding', 'Geocoding', 'Convert addresses to coordinates'],
      ['map-reverse-geocode', 'Reverse Geocoding', 'Get addresses from coordinates'],
      ['map-places', 'Places Search', 'Search for businesses and points of interest'],
      ['map-autocomplete', 'Address Autocomplete', 'Smart address suggestions'],
      ['map-polygon', 'Polygon Drawing', 'Draw custom areas on maps'],
      ['map-polyline', 'Polyline Tool', 'Draw lines and paths on maps'],
      ['map-circle', 'Circle Drawing', 'Add circular areas to maps'],
      ['map-layer', 'Map Layers', 'Toggle different map layers'],
      ['map-wms', 'WMS Integration', 'Web Map Service layer support'],
      ['map-tile', 'Custom Tiles', 'Add custom tile layers'],
      ['map-vector', 'Vector Maps', 'Scalable vector map tiles'],
      ['map-choropleth', 'Choropleth Map', 'Data-driven region coloring'],
      ['map-bubble', 'Bubble Map', 'Size-scaled markers for data visualization'],
      ['map-connection', 'Connection Lines', 'Draw lines between locations'],
      ['map-animation', 'Map Animation', 'Animate movements and transitions'],
      ['map-timeline', 'Temporal Map', 'Show data changes over time'],
      ['map-weather', 'Weather Layer', 'Weather conditions overlay'],
      ['map-terrain', 'Terrain Analysis', 'Topographic and terrain data'],
      ['map-slope', 'Slope Analysis', 'Calculate and visualize slope'],
      ['map-watershed', 'Watershed Analysis', 'Watershed and drainage analysis'],
      ['map-visibility', 'Viewshed Analysis', 'Visibility and line-of-sight'],
      ['map-buffer', 'Buffer Zones', 'Create buffer zones around features'],
      ['map-intersection', 'Spatial Intersection', 'Find overlapping areas'],
      ['map-nearest', 'Nearest Neighbor', 'Find closest points or features'],
      ['map-density', 'Point Density', 'Calculate point density'],
      ['map-hot-spot', 'Hot Spot Analysis', 'Identify clustering patterns'],
      ['map-interpolation', 'Spatial Interpolation', 'Estimate values between points'],
      ['map-network', 'Network Analysis', 'Analyze connected networks'],
      ['map-service-area', 'Service Area', 'Calculate service coverage areas'],
      ['map-location-share', 'Location Sharing', 'Share and track live locations'],
      ['map-check-in', 'Check-in System', 'Location-based check-ins'],
      ['map-store-locator', 'Store Locator', 'Find nearest store locations'],
      ['map-delivery', 'Delivery Tracking', 'Real-time delivery tracking'],
      ['map-fleet', 'Fleet Management', 'Track vehicle fleets'],
      ['map-asset', 'Asset Tracking', 'Monitor asset locations']
    ]
    const [id, name, desc] = maps[i] || maps[0]
    return generateCapsule(id, name, 'Utility', desc, ['map', 'geo', 'location'])
  }),

  // Real-time & Streaming - 50 capsules
  ...Array.from({ length: 50 }, (_, i) => {
    const realtime = [
      ['rt-websocket', 'WebSocket Client', 'Real-time bidirectional communication'],
      ['rt-sse', 'Server-Sent Events', 'One-way real-time updates from server'],
      ['rt-polling', 'Long Polling', 'HTTP long polling for updates'],
      ['rt-pubsub', 'Pub/Sub System', 'Publish-subscribe messaging'],
      ['rt-message-queue', 'Message Queue', 'Async message queue processing'],
      ['rt-event-bus', 'Event Bus', 'Event-driven architecture'],
      ['rt-kafka', 'Kafka Consumer', 'Apache Kafka stream processing'],
      ['rt-rabbitmq', 'RabbitMQ', 'Message broker integration'],
      ['rt-mqtt', 'MQTT Client', 'IoT messaging protocol'],
      ['rt-grpc', 'gRPC Streams', 'Bidirectional streaming RPC'],
      ['rt-graphql-sub', 'GraphQL Subscriptions', 'Real-time GraphQL updates'],
      ['rt-firebase', 'Firebase Realtime', 'Firebase real-time database'],
      ['rt-supabase', 'Supabase Realtime', 'Supabase live updates'],
      ['rt-pusher', 'Pusher Integration', 'Real-time push notifications'],
      ['rt-socket-io', 'Socket.IO', 'Socket.IO client and server'],
      ['rt-notification', 'Live Notifications', 'Real-time notification center'],
      ['rt-chat', 'Live Chat', 'Real-time chat application'],
      ['rt-presence', 'Presence System', 'Track online users'],
      ['rt-typing', 'Typing Indicators', 'Show when users are typing'],
      ['rt-cursor', 'Live Cursors', 'Show user cursor positions'],
      ['rt-collaboration', 'Collaborative Editing', 'Real-time co-editing'],
      ['rt-comments', 'Live Comments', 'Real-time commenting system'],
      ['rt-reactions', 'Live Reactions', 'Real-time emoji reactions'],
      ['rt-feed', 'Activity Feed', 'Live activity stream'],
      ['rt-ticker', 'Stock Ticker', 'Real-time stock prices'],
      ['rt-crypto', 'Crypto Prices', 'Live cryptocurrency data'],
      ['rt-sports', 'Live Sports Scores', 'Real-time sports updates'],
      ['rt-auction', 'Live Auction', 'Real-time bidding system'],
      ['rt-voting', 'Live Polls', 'Real-time voting and polls'],
      ['rt-quiz', 'Live Quiz', 'Interactive live quiz'],
      ['rt-leaderboard', 'Live Leaderboard', 'Real-time rankings'],
      ['rt-counter', 'Live Counter', 'Synchronized counters'],
      ['rt-progress', 'Live Progress', 'Real-time progress tracking'],
      ['rt-status', 'Status Updates', 'Live status monitoring'],
      ['rt-logs', 'Live Logs', 'Streaming log viewer'],
      ['rt-metrics', 'Live Metrics', 'Real-time metrics dashboard'],
      ['rt-alerts', 'Live Alerts', 'Instant alert system'],
      ['rt-dashboard', 'Live Dashboard', 'Real-time data dashboard'],
      ['rt-map', 'Live Map', 'Real-time location tracking'],
      ['rt-video', 'Live Video', 'Live video streaming'],
      ['rt-audio', 'Live Audio', 'Real-time audio streaming'],
      ['rt-screen-share', 'Screen Sharing', 'Real-time screen broadcast'],
      ['rt-whiteboard', 'Live Whiteboard', 'Collaborative whiteboard'],
      ['rt-drawing', 'Shared Drawing', 'Real-time drawing canvas'],
      ['rt-kanban', 'Live Kanban', 'Real-time task board'],
      ['rt-calendar', 'Shared Calendar', 'Collaborative calendar'],
      ['rt-document', 'Live Document', 'Real-time document editing'],
      ['rt-spreadsheet', 'Live Spreadsheet', 'Collaborative spreadsheet'],
      ['rt-code-editor', 'Live Code Editor', 'Real-time code collaboration'],
      ['rt-sync-state', 'State Synchronization', 'Sync app state across clients']
    ]
    const [id, name, desc] = realtime[i] || realtime[0]
    return generateCapsule(id, name, 'Interaction', desc, ['realtime', 'websocket', 'live'])
  }),

  // Security - 50 capsules
  ...Array.from({ length: 50 }, (_, i) => {
    const security = [
      ['sec-authentication', 'Authentication', 'User authentication and login system'],
      ['sec-authorization', 'Authorization', 'Role-based access control'],
      ['sec-oauth', 'OAuth 2.0', 'OAuth authentication provider'],
      ['sec-saml', 'SAML SSO', 'SAML single sign-on'],
      ['sec-jwt', 'JWT Handler', 'JSON Web Token management'],
      ['sec-2fa', 'Two-Factor Auth', '2FA with TOTP/SMS'],
      ['sec-mfa', 'Multi-Factor Auth', 'Multiple authentication factors'],
      ['sec-biometric', 'Biometric Auth', 'Fingerprint and face recognition'],
      ['sec-password-policy', 'Password Policy', 'Enforce password requirements'],
      ['sec-password-strength', 'Password Strength', 'Password strength meter'],
      ['sec-password-reset', 'Password Reset', 'Secure password reset flow'],
      ['sec-session', 'Session Management', 'Secure session handling'],
      ['sec-csrf', 'CSRF Protection', 'Cross-site request forgery protection'],
      ['sec-xss', 'XSS Prevention', 'Cross-site scripting protection'],
      ['sec-sql-injection', 'SQL Injection Guard', 'Prevent SQL injection attacks'],
      ['sec-rate-limit', 'Rate Limiting', 'API rate limiting and throttling'],
      ['sec-ddos', 'DDoS Protection', 'Distributed denial of service mitigation'],
      ['sec-firewall', 'Web Application Firewall', 'WAF rules and filtering'],
      ['sec-encryption', 'Data Encryption', 'Encrypt sensitive data'],
      ['sec-decryption', 'Data Decryption', 'Decrypt encrypted data'],
      ['sec-hashing', 'Password Hashing', 'Secure password hashing'],
      ['sec-salt', 'Salt Generator', 'Generate cryptographic salts'],
      ['sec-key-management', 'Key Management', 'Manage encryption keys'],
      ['sec-certificate', 'SSL/TLS Certificates', 'Certificate management'],
      ['sec-signature', 'Digital Signatures', 'Sign and verify documents'],
      ['sec-token', 'Token Management', 'Secure token generation'],
      ['sec-api-key', 'API Key Management', 'Generate and validate API keys'],
      ['sec-secret', 'Secret Management', 'Store and retrieve secrets'],
      ['sec-vault', 'Secret Vault', 'Hashicorp Vault integration'],
      ['sec-audit-log', 'Security Audit Log', 'Log security events'],
      ['sec-intrusion', 'Intrusion Detection', 'Detect security threats'],
      ['sec-vulnerability', 'Vulnerability Scan', 'Scan for security issues'],
      ['sec-compliance', 'Compliance Check', 'GDPR, HIPAA compliance'],
      ['sec-penetration', 'Pen Testing', 'Security penetration testing'],
      ['sec-malware', 'Malware Detection', 'Scan for malicious code'],
      ['sec-virus', 'Antivirus Scan', 'File virus scanning'],
      ['sec-quarantine', 'File Quarantine', 'Isolate suspicious files'],
      ['sec-sandbox', 'Sandbox Environment', 'Execute code in isolation'],
      ['sec-container', 'Container Security', 'Docker/K8s security'],
      ['sec-network', 'Network Security', 'Network traffic monitoring'],
      ['sec-vpn', 'VPN Integration', 'Virtual private network'],
      ['sec-proxy', 'Security Proxy', 'Reverse proxy with security'],
      ['sec-captcha', 'CAPTCHA', 'Human verification'],
      ['sec-recaptcha', 'reCAPTCHA', 'Google reCAPTCHA integration'],
      ['sec-ip-whitelist', 'IP Whitelist', 'Allow specific IP addresses'],
      ['sec-ip-blacklist', 'IP Blacklist', 'Block malicious IPs'],
      ['sec-geo-blocking', 'Geo-blocking', 'Block by geographic location'],
      ['sec-content-filter', 'Content Filtering', 'Filter inappropriate content'],
      ['sec-data-loss', 'Data Loss Prevention', 'Prevent data leakage'],
      ['sec-backup-encrypt', 'Encrypted Backup', 'Secure encrypted backups']
    ]
    const [id, name, desc] = security[i] || security[0]
    return generateCapsule(id, name, 'Utility', desc, ['security', 'auth', 'protection'])
  })
]

export default extendedCapsulesBatch1
