/**
 * Extended Capsules Batch 9 - 250 capsules
 * Education, E-Learning, Courses, Training, Assessment
 */

import { Capsule } from '@/types/capsule'

const generateCapsule = (id: string, name: string, category: string, desc: string, tags: string[]): Capsule => ({
  id, name, category, description: desc, tags,
  code: `'use client'\nexport default function ${name.replace(/[^a-zA-Z0-9]/g, '')}() {\n  return <div className="p-4 border rounded-lg shadow">${name}</div>\n}`,
  platform: 'react'
})

const extendedCapsulesBatch9: Capsule[] = [
  // E-Learning & Courses - 70 capsules
  ...['edu-course-catalog', 'edu-course-card', 'edu-course-grid', 'edu-course-detail', 'edu-course-preview', 'edu-curriculum-builder', 'edu-lesson-list', 'edu-module-viewer', 'edu-chapter-navigation', 'edu-video-player-edu', 'edu-video-transcript', 'edu-video-chapters', 'edu-video-speed-control', 'edu-video-notes', 'edu-video-bookmarks', 'edu-pdf-viewer-edu', 'edu-document-reader', 'edu-presentation-viewer', 'edu-slide-deck', 'edu-interactive-slides', 'edu-code-playground', 'edu-live-coding', 'edu-code-sandbox', 'edu-code-runner', 'edu-terminal-emulator', 'edu-jupyter-notebook-edu', 'edu-markdown-renderer', 'edu-math-equation-editor', 'edu-latex-renderer', 'edu-diagram-viewer-edu', 'edu-interactive-diagram', 'edu-3d-model-edu', 'edu-simulation', 'edu-virtual-lab', 'edu-experiment-builder', 'edu-progress-tracker-edu', 'edu-completion-badge', 'edu-achievement-system', 'edu-certificate-generator', 'edu-credential-viewer', 'edu-enrollment-form', 'edu-waitlist-manager', 'edu-payment-checkout-edu', 'edu-subscription-plans', 'edu-free-trial', 'edu-coupon-code', 'edu-student-dashboard', 'edu-instructor-dashboard', 'edu-course-analytics', 'edu-engagement-metrics', 'edu-watch-time-tracker', 'edu-drop-off-analysis', 'edu-completion-rate', 'edu-learning-path', 'edu-recommended-courses', 'edu-related-content', 'edu-prerequisite-checker', 'edu-skill-tree', 'edu-learning-goals', 'edu-study-planner', 'edu-deadline-tracker', 'edu-reminder-system-edu', 'edu-calendar-integration', 'edu-office-hours', 'edu-1on1-booking', 'edu-group-sessions', 'edu-live-class', 'edu-webinar-platform', 'edu-breakout-rooms', 'edu-screen-share-edu', 'edu-whiteboard-edu'].map((id) =>
    generateCapsule(id, id.split('-').slice(1).map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' '), 'Media', `${id.split('-').slice(1).join(' ')} education component`, ['education', 'learning', 'course'])
  ),

  // Assessment & Testing - 60 capsules
  ...['quiz-builder', 'quiz-question-bank', 'quiz-multiple-choice', 'quiz-true-false', 'quiz-short-answer', 'quiz-essay-question', 'quiz-matching', 'quiz-fill-blanks', 'quiz-ordering', 'quiz-hotspot', 'quiz-drag-drop-quiz', 'quiz-image-choice', 'quiz-audio-question', 'quiz-video-question', 'quiz-code-challenge', 'quiz-sql-challenge', 'quiz-math-problem', 'quiz-formula-input', 'quiz-drawing-answer', 'quiz-file-upload-quiz', 'quiz-timer-countdown', 'quiz-progress-bar-quiz', 'quiz-question-navigation', 'quiz-flag-review', 'quiz-skip-question', 'quiz-auto-save-quiz', 'quiz-submit-confirmation', 'quiz-instant-feedback', 'quiz-delayed-results', 'quiz-score-display', 'quiz-grade-breakdown', 'quiz-answer-review', 'quiz-explanation-viewer', 'quiz-solution-walkthrough', 'quiz-retry-quiz', 'quiz-practice-mode', 'quiz-exam-mode', 'quiz-time-limit', 'quiz-randomize-questions', 'quiz-randomize-answers', 'quiz-question-pool', 'quiz-adaptive-difficulty', 'quiz-mastery-learning', 'quiz-spaced-repetition', 'quiz-flashcards', 'quiz-study-cards', 'quiz-flip-card', 'quiz-memory-game', 'quiz-knowledge-check', 'quiz-self-assessment', 'quiz-peer-review-quiz', 'quiz-rubric-grader', 'quiz-manual-grading', 'quiz-auto-grading', 'quiz-plagiarism-checker', 'quiz-proctoring-system', 'quiz-lockdown-browser', 'quiz-webcam-monitoring', 'quiz-screen-recording-quiz', 'quiz-analytics-quiz'].map((id) =>
    generateCapsule(id, id.split('-').slice(1).map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' '), 'Form', `${id.split('-').slice(1).join(' ')} assessment component`, ['quiz', 'test', 'assessment'])
  ),

  // Interactive Learning - 60 capsules
  ...['interactive-tutorial', 'interactive-walkthrough', 'interactive-tooltip-edu', 'interactive-hint-system', 'interactive-guided-tour', 'interactive-onboarding', 'interactive-step-by-step', 'interactive-practice-exercise', 'interactive-coding-exercise', 'interactive-debugging-challenge', 'interactive-refactoring-task', 'interactive-design-challenge', 'interactive-case-study', 'interactive-scenario-based', 'interactive-branching-scenario', 'interactive-decision-tree', 'interactive-role-play', 'interactive-conversation-sim', 'interactive-dialogue-tree', 'interactive-choose-adventure', 'interactive-gamification', 'interactive-points-system', 'interactive-leaderboard', 'interactive-badges-edu', 'interactive-levels-progression', 'interactive-xp-tracker', 'interactive-streak-counter-edu', 'interactive-daily-challenge', 'interactive-weekly-quest', 'interactive-achievements-edu', 'interactive-unlockables', 'interactive-rewards-shop', 'interactive-virtual-currency', 'interactive-inventory-system', 'interactive-character-customization', 'interactive-avatar-builder', 'interactive-profile-showcase', 'interactive-social-learning', 'interactive-study-groups', 'interactive-peer-learning', 'interactive-discussion-forum-edu', 'interactive-qa-system-edu', 'interactive-help-center-edu', 'interactive-resource-library', 'interactive-glossary', 'interactive-index-search', 'interactive-citation-tool', 'interactive-bibliography', 'interactive-reference-manager', 'interactive-note-taking', 'interactive-highlight-tool', 'interactive-annotation-system', 'interactive-margin-notes', 'interactive-summary-generator', 'interactive-mind-map-edu', 'interactive-concept-map', 'interactive-knowledge-graph', 'interactive-timeline-edu', 'interactive-progress-visualization', 'interactive-learning-analytics'].map((id) =>
    generateCapsule(id, id.split('-').slice(1).map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' '), 'Interaction', `${id.split('-').slice(1).join(' ')} interactive learning component`, ['interactive', 'learning', 'engagement'])
  ),

  // Student & Instructor Tools - 60 capsules
  ...['student-profile', 'student-portfolio', 'student-transcript', 'student-grade-book', 'student-attendance-tracker', 'student-assignment-list', 'student-submission-portal', 'student-feedback-viewer', 'student-performance-report', 'student-skills-tracker', 'student-competency-map', 'student-iep-tracker', 'student-504-plan', 'student-accommodation-request', 'student-support-resources', 'instructor-course-manager', 'instructor-content-editor', 'instructor-assignment-creator', 'instructor-grading-interface', 'instructor-grade-export', 'instructor-attendance-manager', 'instructor-roster-viewer', 'instructor-student-insights', 'instructor-analytics-dashboard', 'instructor-engagement-report', 'instructor-discussion-moderator', 'instructor-announcement-system', 'instructor-email-students', 'instructor-bulk-messaging', 'instructor-office-hours-scheduler', 'instructor-appointment-booking', 'instructor-feedback-templates', 'instructor-rubric-builder', 'instructor-question-bank-manager', 'instructor-content-library', 'instructor-reusable-modules', 'instructor-course-templates', 'instructor-syllabus-builder', 'instructor-schedule-planner', 'instructor-curriculum-mapping', 'instructor-learning-objectives', 'instructor-standards-alignment', 'instructor-assessment-builder', 'instructor-survey-creator', 'instructor-poll-launcher', 'instructor-peer-review-setup', 'instructor-group-manager', 'instructor-team-assignments', 'instructor-collaboration-tools', 'instructor-plagiarism-report', 'instructor-grade-distribution', 'instructor-class-statistics', 'instructor-completion-tracking', 'instructor-extension-requests', 'instructor-late-submission-policy', 'instructor-grade-override', 'instructor-curve-calculator', 'instructor-weighted-grades', 'instructor-extra-credit', 'instructor-bonus-points'].map((id) =>
    generateCapsule(id, id.split('-').slice(1).map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' '), 'Dashboard', `${id.split('-').slice(1).join(' ')} educational tool`, ['education', 'teaching', 'learning'])
  )
]

export default extendedCapsulesBatch9
